services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - .:/workspace
    working_dir: /workspace/backend
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    env_file:
      - ./backend/.env  # Added this line to load the .env file

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true